#!/usr/bin/env python3
"""The check registry, generated from src/sources.txt.

    python tools/register_gen.py src/sources.txt build/gen

Writes build/gen/register.c from the manifest's [tests] section, in order.
The filename is the contract: tests/base/test_json.c must define
test_json_register(void).
"""
import os
import sys


def sections(path):
    """{name: [line, ...]} from a [section] file, order preserved."""
    out, cur = {}, None
    with open(path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("[") and line.endswith("]"):
                cur = line[1:-1]
                out.setdefault(cur, [])
                continue
            if cur is not None:
                out[cur].append(line)
    return out


def name_of(path):
    """tests/base/test_json.c -> json"""
    leaf = os.path.basename(path)
    stem = leaf[:-2] if leaf.endswith(".c") else leaf
    if not stem.startswith("test_"):
        raise SystemExit(
            "register_gen: %s is in [tests] but is not named test_*.c -- the "
            "filename is what names its register function" % path)
    return stem[len("test_"):]


def main(argv):
    if len(argv) != 3:
        raise SystemExit("usage: register_gen.py <sources.txt> <outdir>")
    manifest, outdir = argv[1], argv[2]

    tests = sections(manifest).get("tests", [])
    if not tests:
        raise SystemExit("register_gen: [tests] is empty in %s" % manifest)

    names = [name_of(p) for p in tests]

    lines = [
        "/* GENERATED by tools/register_gen.py from src/sources.txt -- do not edit.",
        " *",
        " * Every check this build ships, in the order they run. The manifest is",
        " * the one place that list exists.",
        " */",
        "",
        '#include "tools/selftest.h"',
        "",
    ]
    lines += ["void test_%s_register(void);" % n for n in names]
    lines += [
        "",
        "void tests_register_all(void) {",
    ]
    lines += ["    test_%s_register();" % n for n in names]
    lines += ["}", ""]
    text = "\n".join(lines)

    os.makedirs(outdir, exist_ok=True)
    out = os.path.join(outdir, "register.c")
    # Only when it changed: an unconditional write makes every build recompile
    # this and relink, which on the console is the slow half.
    try:
        with open(out, "r", encoding="utf-8") as f:
            if f.read() == text:
                return 0
    except OSError:
        pass
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
